modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="pipboy"
version="1.0.0.1"
displayName="Create: Pipboy"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-pipboy"
logoFile="logo.png"
credits="Bethesta, Fallout Games"
authors="JxstCris"
description="Pipboy 3000 from Fallout!"

[[dependencies.pipboy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.pipboy]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pipboy]]
    modId="create"
    mandatory=true
    versionRange="[6.0.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pipboy]]
    modId="create_new_age"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


